services:
  api-gateway:
    image: kong:latest
    container_name: ki-enterprise-api-gateway
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
    volumes:
      - ../../infrastructure/api-gateway/kong.yml:/usr/local/kong/declarative/kong.yml
    networks:
      - ki-enterprise
networks:
  ki-enterprise:
    external: true
