services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ki-enterprise-rabbitmq
    restart: unless-stopped
    hostname: rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: ki
      RABBITMQ_DEFAULT_PASS: StrongPassword123!

    ports:
      - "15672:5672"
      - "15673:15672"

    volumes:
      - ../../storage/rabbitmq:/var/lib/rabbitmq

    networks:
      - ki-enterprise

    healthcheck:
      test: ["CMD","rabbitmq-diagnostics","check_port_connectivity"]
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  ki-enterprise:
    external: true
